theme: jekyll-theme-minimal
title: Daniel Weddle
description: Interested in Data Science, National Security, Education
logo: https://media-exp1.licdn.com/dms/image/C5603AQGtt5T6qw-1UQ/profile-displayphoto-shrink_800_800/0/1629050342858?e=1636588800&v=beta&t=ToKhe0tSGl_ZDNarPX-GpPiUgT1-YP4qxyAwNsgNlcQ
